setup:

run-hw2-dfa:
	python3 dfa.py
run-hw2-dfalang:
	python3 dfalang.py
run-hw2-dfa2xml:
	python3 dfaxml.py
run-hw2-union:
	python3 dfaunion.py
run-hw2-intersection:
	python3 dfaintersection.py